# Generated by Django 4.2.7 on 2025-10-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AlterModelOptions(
            name='approvallog',
            options={'verbose_name': 'Запись согласования', 'verbose_name_plural': 'Записи согласования'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Праздничный день', 'verbose_name_plural': 'Праздничные дни'},
        ),
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'verbose_name': 'Заявка на переработку', 'verbose_name_plural': 'Заявки на переработку'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime_app.employee', verbose_name='Согласующий'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='decision',
            field=models.CharField(choices=[('approved', 'Согласовано'), ('rejected', 'Не согласовано')], max_length=20, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='overtime_app.overtimerequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='management',
            field=models.CharField(blank=True, max_length=200, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates1', to='overtime_app.employee', verbose_name='Руководитель 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates2', to='overtime_app.employee', verbose_name='Руководитель 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overtime_app.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime_app.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='hours',
            field=models.FloatField(editable=False, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='justification',
            field=models.TextField(verbose_name='Обоснование'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='reason',
            field=models.CharField(choices=[('holiday', 'Работа в выходной и праздничный день'), ('incident', 'Работы по устранению инцидентов'), ('maintenance', 'Регламентные работы по обслуживанию системы')], max_length=200, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overtime_app.role', verbose_name='Роль'),
        ),
    ]
