# Generated by Django 4.2.7 on 2025-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0004_role_alter_approvallog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_unit',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='management',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отдел'),
        ),
    ]
