# Generated by Django 4.2.7 on 2025-10-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0005_remove_employee_department_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
