# Generated by Django 4.2.7 on 2025-10-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0006_remove_employee_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime_app.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime_app.overtimerequest')),
            ],
        ),
    ]
