# Generated by Django 4.2.7 on 2025-10-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0007_approvaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='overtime_attachments/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
