# Generated by Django 4.2.7 on 2025-10-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0008_overtimerequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
