# Generated by Django 4.2.7 on 2025-10-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0009_alter_overtimerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title_manual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность (ручная)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель')], default='employee', max_length=20, verbose_name='Тип роли (Руководитель/Сотрудник)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overtime_app.position', verbose_name='Должность (ролевая)'),
        ),
    ]
