# Generated by Django 4.2.7 on 2025-10-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0010_employee_job_title_manual_employee_role_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title_manual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель')], default='employee', max_length=20, verbose_name='Роль (Руководитель/Сотрудник)'),
        ),
    ]
