# Generated by Django 4.2.7 on 2025-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0011_remove_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'verbose_name': 'Заявка на переработку', 'verbose_name_plural': 'Зяки на переработку'},
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='reason',
            field=models.CharField(choices=[('holiday', 'Работа в выходной и праздничный день'), ('incident', 'Работы по устранению инцидентов'), ('maintenance', 'Регламентные работы по обслуживанию системы'), ('on_call', 'Дежурство в торговые выходные дни')], max_length=200, verbose_name='Причина'),
        ),
    ]
