# Generated by Django 4.2.7 on 2025-11-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_app', '0012_alter_overtimerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'verbose_name': 'Заявка на переработку', 'verbose_name_plural': 'Заявки на переработку'},
        ),
    ]
